### ISSUE TITLE
ログインしなくてもコンテンツが閲覧できるようにする

### ISSUE THREAD

**Issue by yhirano55** [railsdm/ama#22]
## TODO

- [ ] Remove needless controllers
- [x] Add sign in suggestion
- [x] Display terms if user is not authenticated
